In [131]:
import pandas as pd
import pymysql

0       21.9
1       23.1
2       25.3
3       24.6
4       23.9
        ...
2482    23.6
2483    21.5
2484    21.2
2485    25.3
2486    24.5
Name: 온도(C), Length: 2487, dtype: object

In [132]:
df = pd.read_csv('TeamAPI.csv', encoding='cp949') 
df
#df.to_csv("pro1.csv")

,데이터 시간,시리얼번호,미세먼지(/),초미세먼지(/),이산화탄소(ppm),휘발성유기화합물(ppb),온도(C),습도(%),소음(dB),통합실내지수
0,2024-03-21 15:04,ICW0W2100481,10,4,1277,5282,21.9,32,72,68
1,2024-03-21 15:04,ICW0W2100582,28,10,694,119,23.1,20,71,94
2,2024-03-21 15:04,ICW0W2100579,9,3,0,446,25.3,13,61,87
3,2024-03-21 15:05,ICW0W2100562,27,14,581,4762,24.6,15,68,62
4,2024-03-21 15:04,ICW0W2100560,13,4,582,6000,23.9,17,59,65
...,...,...,...,...,...,...,...,...,...,...
2482,2024-04-02 10:59,ICW0W2100488,39,14,419,52,23.6,15,75,92
2483,2024-04-02 10:59,ICW0W2100506,0,0,33,12,21.5,18,62,100
2484,2024-03-29 10:41,ICW0W2100582,89,21,682,148,21.2,33,80,86
2485,2024-04-02 10:59,ICW0W2100579,23,9,0,161,25.3,15,57,92
2486,2024-04-02 11:01,ICW0W2100562,29,15,708,1248,24.5,18,62,69

In [100]:
#df.loc[df['미세먼지(/)'].isdigit()]

#문자가 들어간 행번호(index)를 저장하기 위한 리스트
idxList = []

#enumerate : 반복문에 index 생성 - 인덱스를 구하기 위해 사용.

for idx, each in enumerate(df['미세먼지(/)']):
    #print(idx, each)

    # isdigit : 해당 데이터를 숫자로 변환가능한지 여부 판단(true , false)
    # 숫자로 변환하지 못하는 데이터를 뽑아 행 번호를 저장하기 위한 리스트에 담아줌.
    if not each.isdigit():
        idxList.append(idx)
   
idxList
###########################################################
# 데이터 (행 , 열) 갯수 확인하기
# df.shape

# df.info()
# df.replace('데이터')
#df = df[~df['데이터 시간'].str.contains('데이터 시간')]

#df.to_csv("test4.csv")

[72,
 145,
 218,
 291,
 364,
 437,
 510,
 583,
 656,
 729,
 802,
 875,
 948,
 1021,
 1094,
 1167,
 1240,
 1313,
 1386,
 1459,
 1532,
 1605,
 1678,
 1751,
 1824,
 1897,
 1970,
 2043,
 2117,
 2191,
 2265,
 2339,
 2413]

In [5]:
#문자가 들어간 행 삭제
df.drop(index=idxList, inplace=True)

#####################################################
# 중복된 데이터 삭제
#df2 = df.drop_duplicates()

# 중복된 데이터저장 후 확인해보기
#df2.to_csv("test1.csv")

KeyError: '[87, 175, 263, 351, 439, 527, 615, 703, 791, 879, 967, 1055, 1143, 1231, 1319, 1407, 1495, 1583, 1671, 1759, 1847, 1935, 2023, 2111, 2199, 2287, 2375, 2463, 2551, 2639, 2727, 2815, 2903] not found in axis'

In [133]:
#문자가 들어간 행번호(index)를 저장하기 위한 리스트
idxList = []

for idx, each in enumerate(df['미세먼지(/)']):
    #print(idx, each)
    if not each.isdigit():
        idxList.append(idx)
   
idxList

df.drop(index=idxList, inplace=True)

df

,데이터 시간,시리얼번호,미세먼지(/),초미세먼지(/),이산화탄소(ppm),휘발성유기화합물(ppb),온도(C),습도(%),소음(dB),통합실내지수
0,2024-03-21 15:04,ICW0W2100481,10,4,1277,5282,21.9,32,72,68
1,2024-03-21 15:04,ICW0W2100582,28,10,694,119,23.1,20,71,94
2,2024-03-21 15:04,ICW0W2100579,9,3,0,446,25.3,13,61,87
3,2024-03-21 15:05,ICW0W2100562,27,14,581,4762,24.6,15,68,62
4,2024-03-21 15:04,ICW0W2100560,13,4,582,6000,23.9,17,59,65
...,...,...,...,...,...,...,...,...,...,...
2482,2024-04-02 10:59,ICW0W2100488,39,14,419,52,23.6,15,75,92
2483,2024-04-02 10:59,ICW0W2100506,0,0,33,12,21.5,18,62,100
2484,2024-03-29 10:41,ICW0W2100582,89,21,682,148,21.2,33,80,86
2485,2024-04-02 10:59,ICW0W2100579,23,9,0,161,25.3,15,57,92
2486,2024-04-02 11:01,ICW0W2100562,29,15,708,1248,24.5,18,62,69

In [134]:
import pymysql

In [135]:
conn = pymysql.connect(host='localhost', user='studyroom', passwd='studyroom' ,db='studyroom', charset='utf8')
cursor = conn.cursor(pymysql.cursors.DictCursor)

In [136]:
#df = df.iloc[0: ,[0,1,6,7]]


#df.columns=[['데이터 시간','SERIAL_NO','TEMPERATURE', 'HUMIDITY']]
df=df[['데이터 시간','시리얼번호','온도(C)', '습도(%)']]

#df

In [121]:

#df.index = range(len(df))

         SERIAL_NO
0     ICW0W2100481
1     ICW0W2100582
2     ICW0W2100579
3     ICW0W2100562
4     ICW0W2100560
...            ...
2449  ICW0W2100488
2450  ICW0W2100506
2451  ICW0W2100582
2452  ICW0W2100579
2453  ICW0W2100562

[2454 rows x 1 columns]

In [137]:
df['온도(C)'] = pd.to_numeric(df['온도(C)'])
df['습도(%)'] = pd.to_numeric(df['습도(%)'])
#df['HUMIDITY'].series()
#pd.to_numeric(df['TEMPERATURE'])


#pd.to_numeric(df.TEMPERATURE.values.tolist())
#df.TEMPERATURE.values
#df['TEMPERATURE'][0]

#for each in df['TEMPERATURE']:
#    print(each)

C:\Users\GRS\AppData\Local\Temp\ipykernel_11972\433354845.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['온도(C)'] = pd.to_numeric(df['온도(C)'])
C:\Users\GRS\AppData\Local\Temp\ipykernel_11972\433354845.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['습도(%)'] = pd.to_numeric(df['습도(%)'])

In [138]:
DATE_TIME = df['데이터 시간']
TEMPERATURE = df['온도(C)']
SERIAL_NO = df['시리얼번호']
HUMIDITY = df['습도(%)']

TEMPERATURE
df

                데이터 시간         시리얼번호  온도(C)  습도(%)
0     2024-03-21 15:04  ICW0W2100481   21.9     32
1     2024-03-21 15:04  ICW0W2100582   23.1     20
2     2024-03-21 15:04  ICW0W2100579   25.3     13
3     2024-03-21 15:05  ICW0W2100562   24.6     15
4     2024-03-21 15:04  ICW0W2100560   23.9     17
...                ...           ...    ...    ...
2482  2024-04-02 10:59  ICW0W2100488   23.6     15
2483  2024-04-02 10:59  ICW0W2100506   21.5     18
2484  2024-03-29 10:41  ICW0W2100582   21.2     33
2485  2024-04-02 10:59  ICW0W2100579   25.3     15
2486  2024-04-02 11:01  ICW0W2100562   24.5     18

[2454 rows x 4 columns]

In [146]:
#len(df)
#df.index = range(len(df))
df.to_excel('aaa.xlsx')

In [145]:
for i in range(len(df)):
    sql=f"INSERT INTO TEMANDHUM (DATE_TIME, SERIAL_NO, TEMPERATURE, HUMIDITY) VALUES ('{DATE_TIME[i]}', '{SERIAL_NO[i]}', {TEMPERATURE[i]}, {HUMIDITY[i]})"
    cursor.execute(sql)

conn.commit()

KeyError: 72